[tools]
go = "1.24"
node = "latest"

"aqua:neovim/neovim" = "latest"

# go tools
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"

# lua tools
"github:luals/lua-language-server" = { version = "latest", extract_all = true, bin_path = "bin" }

# node tools
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

# python tools
"github:astral-sh/uv" = "latest"

"github:jesseduffield/lazygit" = "latest"
"github:alexpasmantier/television" = { version = "latest", exe = "tv" }
"github:sharkdp/fd" = "latest"
"github:sharkdp/bat" = "latest"
"github:cli/cli" = { version = "latest", exe = "gh" }
"github:nektos/act" = "latest"
"github:ducaale/xh" = "latest"

[settings]
experimental = true

trusted_config_paths = ["~/Code"]
idiomatic_version_file_enable_tools = ["node"]
