[tools]
go = "1.24"
node = "latest"

"ubi:neovim/neovim" = { version = "latest", extract_all = true, bin_path = "bin" }

# go tools
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"

# lua tools
"ubi:luals/lua-language-server" = { version = "latest", extract_all = true, bin_path = "bin" }

# node tools
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

# python tools
"ubi:astral-sh/uv" = "latest"
uv = "latest"
action-validator = "latest"

"ubi:jesseduffield/lazygit" = "latest"
"ubi:alexpasmantier/television" = { version = "latest", exe = "tv" }
"ubi:sharkdp/fd" = "latest"
"ubi:sharkdp/bat" = "latest"
"ubi:cli/cli" = { version = "latest", exe = "gh" }
"ubi:nektos/act" = "latest"
"ubi:ducaale/xh" = "latest"
"ubi:dandavison/delta" = "latest"

[settings]
experimental = true

trusted_config_paths = ["~/Code"]
idiomatic_version_file_enable_tools = ["node"]
